FROM nginx:alpine

#Arquivos copiados
COPY escopo.html /usr/share/nginx/html/
COPY css/style.css /usr/share/nginx/html/
COPY images/230344.png /usr/share/nginx/html/
COPY images/Cômoda-retrô-com-espelho.jpg /usr/share/nginx/html/
COPY images/Fundo.jpg /usr/share/nginx/html/
COPY images/moveis-retro-roxo-vibrante-na-poltrona.jpg /usr/share/nginx/html/
COPY images/recamier-los-1.jpg /usr/share/nginx/html/

#Porta Nginx
EXPOSE 80

# Comando para iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]